FROM node:18-alpine AS build
WORKDIR /app
COPY ruoyi-vue-liteflow-ui/package*.json ./
RUN npm install --registry=https://registry.npmmirror.com
COPY ruoyi-vue-liteflow-ui/ .
RUN npm run build:prod

FROM nginx:1.25-alpine
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
